#!/usr/bin/env zsh
# A script for installing dependencies and setting up needed Symbolic Links
# Created by Jeremy Winterberg, Brandon Roehl
# Updated 08/14/2017
# NOTICE: Modify script to your own preferences! This mostly uses default
#         locations, but can be changed to whatever you need.

git submodule init
git submodule update --recursive

if [ hash brew >/dev/null 2>&1 ]
then
  echo 'Attempting to install brew'
  if [ uname = "Darwin" ]
  then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    sudo apt-get install build-essential curl git python-setuptools ruby
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
  fi
fi
brew install zsh git coreutils vim tmux wget bash the_silver_searcher reattach-to-user-namespace zsh-syntax-highlighting

# Check if Oh My ZSH is installed
if ! [ -d "$HOME/.oh-my-zsh/" ]; then
  echo >&2 "oh-my-zsh is not installed, fixing that...";
  curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi

echo 'install rvm or upgrade rvm'
curl -sSL https://get.rvm.io | bash -s stable
if [ hash rvm >/dev/null 2>&1 ]
then
  rvm cleanup all
fi

# Fancy ls script taken from github.com/brandonroehl/dotfiles
files=( 'vimrc' 'vim' 'zshrc' 'zsh' 'tmux.conf' 'tmux-dev.sh' 'tmux-osx' 'agignore' 'gitconfig' 'gitignore' 'gitmessage' 'gemrc' 'rspec' 'eslintrc' )
for file in $files
do
  echo ""
  echo "Simlinking $file to $HOME"
  ln -sf "$PWD/$file" "$HOME/.$file"
  if [ $? -eq 0 ]
  then
    echo "$PWD/$file ~> $HOME/.$file"
  else
    echo 'Install failed to symlink.'
    exit 1
  fi
done
