#!/usr/bin/env zsh
# A script for installing dependencies and setting up needed Symbolic Links
# Created by Jeremy Winterberg
# Updated 12/12/2019

git submodule init
git submodule update --recursive

if [ hash brew >/dev/null 2>&1 ]
then
  echo 'Attempting to install brew'
  if [ uname = "Darwin" ]
  then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install reattach-to-user-namespace 
  else
    sudo apt-get install build-essential curl git python-setuptools ruby
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  fi
fi
brew install zsh git coreutils python tmux wget bash the_silver_searcher zsh-syntax-highlighting
pip3 install neovim

# Check if Oh My ZSH is installed
if ! [ -d "$HOME/.oh-my-zsh/" ]; then
  echo >&2 "oh-my-zsh is not installed, fixing that..."
  curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi

echo 'install rvm or upgrade rvm'
curl -sSL https://get.rvm.io | bash -s stable
if [ hash rvm >/dev/null 2>&1 ]
then
  rvm cleanup all
fi

echo >&2 "Setting ZSH as default shell"
chsh -s /bin/zsh

# Check if z tool is installed
if ! [ -d "$HOME/.dotfiles/z/z.sh" ]; then
  echo >&2 "z is not installed, fixing that..."
  git clone https://raw.github.com/rupa/z.git $HOME/.dotfiles/z
fi

# Fancy ls script taken from github.com/brandonroehl/dotfiles
files=( 'vimrc' 'vim' 'zshrc' 'zsh' 'tmux.conf' 'tmux-osx.conf' 'agignore' 'gitconfig' 'gitignore' 'gitmessage' 'gemrc' 'rspec' 'eslintrc' )
for file in $files
do
  echo ""
  echo "Simlinking $file to $HOME"
  ln -sf "$PWD/$file" "$HOME/.$file"
  if [ $? -eq 0 ]
  then
    echo "$PWD/$file ~> $HOME/.$file"
  else
    echo 'Install failed to symlink.'
    exit 1
  fi
done

echo >&2 "Remember to set vimrc to work with neovim!"
