#!/usr/bin/env zsh

HOME_FOLDERS="bin,configs,tmux"
CONFIG_FOLDERS="nvim,i3,kitty"
DOTFILES=$HOME/.dotfiles

Help()
{
  # Display Help
  echo "Quick script for stowing symlinks for configured dotfiles"
  echo "If c is not passed, it will create symlinks."
  echo
  echo "Syntax: ./stow-run [-h,-c]"
  echo "options:"
  echo "h     Print this Help."
  echo "c     Clean (remove) symlinks."
}

CLEAN=false
while getopts "hc" option; do
  case $option in
    c)
      CLEAN=true
      ;;
    h) Help
      exit
  esac
done

pushd $DOTFILES
for folder in $(echo $HOME_FOLDERS | sed "s/,/ /g")
do
  if [ "$CLEAN" = true ]; then
    stow -D $folder
  else
    stow $folder
  fi
done
for folder in $(echo $CONFIG_FOLDERS | sed "s/,/ /g")
do
  if [ "$CLEAN" = true ]; then
    stow -D $folder -t ~/.config
  else
    stow $folder -t ~/.config
  fi
done
popd
