- name: "Karabiner | Install Karabiner-Elements"
  community.general.homebrew_cask:
    name: karabiner-elements
    state: latest

- name: "Karabiner | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_facts['user_dir'] }}/.config/karabiner"
    state: directory

- name: "Karabiner | Create symlink to config file"
  ansible.builtin.file:
    src: "{{ role_path }}/files/karabiner.json"
    dest: "{{ ansible_facts['user_dir'] }}/.config/karabiner/karabiner.json"
    state: link
    force: true
