require("plugins.telescope")
require("plugins.treesitter")
-- require("plugins.galaxyline")
-- require("plugins.galaxylinewhitewolf")
-- require("plugins.statusline")
-- require("configs.harpoon")
-- require("configs.lsp")
