- name: "Ghostty | Install Ghostty"
  community.general.homebrew_cask:
    name: ghostty
    state: present

- name: "Ghostty | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/ghostty"
    state: directory

- name: "Ghostty | Create symlink to config file"
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: "{{ ansible_user_dir }}/.config/ghostty/config"
    state: link
    force: true
