- name: "Tmux | Install Tmux"
  community.general.homebrew:
    name: tmux
    state: head

- name: "Tmux | Copy tmux files"
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux"
    dest: "{{ ansible_user_dir }}/.config/tmux"
    state: link
    force: true

- name: "TMUX | Install TPM Plugin Manager"
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
