inherit_gem:
  rubocop-shopify: rubocop.yml

require:
 - rubocop-sorbet
 - rubocop-minitest
 - rubocop-rake

Naming/FileName:
  Exclude:
  - "lib/ruby-lsp.rb"

Sorbet/FalseSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: true
  Include:
    - "test/**/*.rb"
  Exclude:
    - "**/*.rake"
    - "lib/**/*.rb"

Sorbet/StrictSigil:
  Enabled: true
  Include:
    - "lib/**/*.rb"
  Exclude:
    - "**/*.rake"
    - "test/**/*.rb"
    - "lib/ruby-lsp.rb"

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  Exclude:
    - 'features/**/*'
    - 'test/fixtures/**/*'
    - '**/*.ru'
    - 'bin/**'
    - 'db/migrations/*'
    - 'explore/**/*'
    - 'vendor/**/*'
    - 'cookbooks/**/*'
    - 'lib/protos/**/*'
    - 'lib/api-ex_services_pb.rb'
    - 'lib/api-ex_pb.rb'
Style/Documentation:
  Enabled: false
Style/GlobalVars:
  AllowedVariables:
    - $redis
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/BeginEndAlignment:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: false
Lint/DuplicateRequire:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
# TODO: decide what to do about HashAlignment. 197 warnings at the time this cop was added
Layout/HashAlignment:
  Enabled: false
Lint/IdentityComparison:
  Enabled: false
Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['\A#']
Lint/MissingSuper:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/NonLocalExitFromIterator:
  Enabled: false
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/SafeNavigationConsistency:
  Enabled: false
Lint/SelfAssignment:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/UnreachableCode:
  Enabled: false
Lint/UnreachableLoop:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: false
Lint/UselessTimes:
  Enabled: true
Style/IfUnlessModifier:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'lib/api_docs.rb'
    - 'lib/api_docs/**'
    - 'apps/**/routes/*.rb'
    - 'apps/*/application.rb'
    - 'db/migrations/*'
    - 'lib/tasks/*.rb'
    - 'mailers/**/*.rb'
    - 'Rakefile'
    - 'resources/**/schemas.rb'
    - 'resources/**/schemas/*.rb'
    - 'spec/**/*.rb'
    - 'config/init/*.rb'
Metrics/CyclomaticComplexity:
  Enabled: false
  Exclude:
    - 'lib/api_docs.rb'
    - 'lib/api_docs/**/*.rb'
    - 'config/init/*.rb'
Metrics/AbcSize:
  Enabled: false
  Exclude:
    - 'lib/api_docs.rb'
    - 'lib/api_docs/**/*.rb'
    - 'config/init/*.rb'
Metrics/PerceivedComplexity:
  Enabled: false
  Exclude:
    - 'lib/api_docs.rb'
    - 'lib/api_docs/**/*.rb'
    - 'config/init/*.rb'
Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'lib/api_docs.rb'
    - 'lib/api_docs/**/*.rb'
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'lib/api_docs.rb'
    - 'lib/api_docs/**'
    - 'config/init/*.rb'
Metrics/ModuleLength:
  Max: 200
  Exclude:
    - spec/**/*
Metrics/ParameterLists:
  CountKeywordArgs: false
Naming/BlockParameterName:
  Enabled: false
Naming/FileName:
  Exclude:
    - cookbooks/**/*
    - deploy/*
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/Alias:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: true
Style/BlockDelimiters:
  Exclude:
    - external/outertrust/client/**/*
Style/CaseLikeIf:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassMethodsDefinitions: # to use self_class methods
  Enabled: true
Style/ClassVars:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/RedundantAssignment:
  Enabled: true
Style/RedundantBegin:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/RedundantSelfAssignment:
  Enabled: true
Style/RedundantSort:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SlicingWithRange: # requires Ruby 2.6
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
