#!/bin/bash

project_path=`git rev-parse --show-toplevel 2> /dev/null`

if [ "$1" == "pull" ]; then
	rsync -avzOLP --delete --cvs-exclude --exclude=/vendor --exclude=/.git \
		$REMOTE_INSTANCE_URL:$REMOTE_PROJECT_PATH $project_path
else
	rsync -avzOLP --delete --exclude=/vendor  --exclude=/.git \
		$project_path/ $REMOTE_INSTANCE_URL:$REMOTE_PROJECT_PATH
fi
