vim.api.nvim_set_keymap('n', '<C-m>', '<cmd>lua require("harpoon.mark").add_file()<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-e>', '<cmd>lua require("harpoon.ui").toggle_quick_menu()<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-Left>', '<cmd>lua require("harpoon.ui").nav_file(1)<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-Down>', '<cmd>lua require("harpoon.ui").nav_file(2)<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-Up>', '<cmd>lua require("harpoon.ui").nav_file(3)<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-Right>', '<cmd>lua require("harpoon.ui").nav_file(4)<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-g>', '<cmd>lua require("harpoon.mark").rm_file()<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader><C-r>', '<cmd>lua require("harpoon.mark").shorten_list()<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader><C-d>', '<cmd>lua require("harpoon.mark").clear_all()<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>r', '<cmd>lua require("harpoon.mark").promote()<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>tu', '<cmd>lua require("harpoon.term").gotoTerminal(1)<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>te', '<cmd>lua require("harpoon.term").gotoTerminal(2)<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>cu', '<cmd>lua require("harpoon.term").sendCommand(1, 1)<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>ce', '<cmd>lua require("harpoon.term").sendCommand(1, 2)<CR>', { noremap = true, silent = true})
