- name: "Neovim | Install Tree-sitter"
  community.general.homebrew:
    name: tree-sitter
    state: head

- name: "Neovim | Install Luajit"
  community.general.homebrew:
    name: luajit
    state: head

- name: "Neovim | Install Neovim"
  community.general.homebrew:
    name: neovim
    state: head

- name: "Neovim | Install Silicon"
  community.general.homebrew:
    name: silicon
    state: present

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
